[build-system]
requires = ["setuptools >= 61.2.0", "wheel >= 0.37.1", "pytest == 7.1.2", "mypy == 0.910"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
# After 3.1 release, with the -o option in the bootstrap directory.
# We can change this to *also* bootstrap the next release 
# From the 3.1 release as part of the tox test suite.
[tox]
envlist = py310

[testenv]
deps = 
    pytest == 7.1.2
    mypy == 0.961
setenv = 
    PYTHONPATH = {toxinidir}/src
commands_pre = 
    python3 src/pyweb.py -o tests tests/pyweb_test.w 
commands = 
    pytest
	mypy --strict --show-error-codes src
"""
