
[build-system]
requires = ["setuptools >= 61.2.0", "wheel >= 0.37.1", "pytest == 7.1.2", "mypy == 0.910"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py310

[testenv]
deps = 
    pytest == 7.1.2
    mypy == 0.910
setenv = 
    PYLPWEB_BOOTSTRAP = bootstrap/pyweb.py
    PYTHONPATH = {toxinidir}
commands_pre = 
    python3 {env:PYLPWEB_BOOTSTRAP} pyweb.w
    python3 pyweb.py -o tests tests/pyweb_test.w 
commands = 
    pytest
	mypy --strict --show-error-codes pyweb.py tangle.py weave.py
"""
